In [9]:
import pickle
import numpy as np

# Ler dados
fN = '/Users/anaso/Documents/AA/AA-22-23/FichasCasa/Ficha3/A39275_Ficha3_Respostas.p'
QuestDic = pickle.load(open(fN, 'rb'))

print(QuestDic.keys())
for quest in QuestDic:
    print(quest, ": ", QuestDic[quest], "\n")


dict_keys(['Q001', 'nome', 'numero'])
Q001 :  [[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]] 

nome :  Ana Sofia Preto Oliveira 

numero :  A39275 



In [7]:
# Editar respostas
QuestDic['Q001'][0, :] = np.array([1, 0, 0, 0])
QuestDic['Q001'][1, :] = np.array([0, 0, 0, 1])
QuestDic['Q001'][2, :] = np.array([0, 0, 0, 1])
QuestDic['Q001'][3, :] = np.array([0, 1, 0, 0])
QuestDic['Q001'][4, :] = np.array([1, 0, 0, 0])
QuestDic['Q001'][5, :] = np.array([0, 1, 0, 0])
QuestDic['Q001'][6, :] = np.array([0, 1, 0, 0])
QuestDic['Q001'][7, :] = np.array([1, 0, 0, 0])
QuestDic['Q001'][8, :] = np.array([0, 0, 0, 1])
QuestDic['Q001'][9, :] = np.array([0, 1, 0, 0])

# Ver respostas
for quest in QuestDic:
    print(quest, ": \n", QuestDic[quest], "\n")

Q001 : 
 [[1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [0. 1. 0. 0.]] 

nome : 
 Ana Sofia Preto Oliveira 

numero : 
 A39275 



In [8]:
# Guardar Respostas
pickle.dump(QuestDic,open(fN,'wb'))