In [1]:
import pickle
import numpy as np

# Ler dados
fN = '/Users/anaso/Documents/AA/AA-22-23/FichasCasa/Ficha1/A39275_Ficha1_Respostas.p'
QuestDic = pickle.load(open(fN, 'rb'))

print(QuestDic.keys())
for quest in QuestDic:
    print(quest, ": ", QuestDic[quest], "\n")


dict_keys(['Q001', 'Q002', 'Q003', 'nome', 'numero'])
Q001 :  [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]] 

Q002 :  [[0. 1. 0. 0.]
 [0. 0. 1. 0.]] 

Q003 :  [[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]] 

nome :  Ana Sofia Preto Oliveira 

numero :  A39275 



In [26]:
# Editar respostas
QuestDic['Q001'][0, :] = np.array([1, 0, 0, 0])
QuestDic['Q001'][1, :] = np.array([0, 1, 0, 0])
QuestDic['Q001'][2, :] = np.array([1, 0, 0, 0])

QuestDic['Q002'][0, :] = np.array([0, 1, 0, 0])
QuestDic['Q002'][1, :] = np.array([0, 0, 1, 0])

QuestDic['Q003'][0, :] = np.array([0, 0, 1, 0])
QuestDic['Q003'][1, :] = np.array([0, 0, 0, 1])
QuestDic['Q003'][2, :] = np.array([0, 0, 0, 1])
QuestDic['Q003'][3, :] = np.array([1, 0, 0, 0])


# Ver respostas
for quest in QuestDic:
    print(quest, ": \n", QuestDic[quest], "\n")

Q001 : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]] 

Q002 : 
 [[0. 1. 0. 0.]
 [0. 0. 1. 0.]] 

Q003 : 
 [[0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]] 

nome : 
 Ana Sofia Preto Oliveira 

numero : 
 A39275 



In [27]:
# Guardar Respostas
pickle.dump(QuestDic,open(fN,'wb'))